docs: update 00QUICKSTART for exit code handling
Document the new -Q option, as well as more details about how failing
to find search terms will result in an error code.

diff --git a/00QUICKSTART b/00QUICKSTART
--- a/00QUICKSTART
+++ b/00QUICKSTART
@@ -739,17 +739,23 @@
 16. The Lsof Exit Code and Shell Scripts
 ========================================
 
-  When lsof exits successfully it returns an exit code based on
+  When lsof executes successfully, it returns an exit code based on
   the result of its search for specified files.  (If no files were
   specified, then the successful exit code is 0 (zero).)
 
   If lsof was asked to search for specific files, including any
   files on specified file systems, it returns an exit code of 0
   (zero) if it found all the specified files and at least one file
-  on each specified file system.  Otherwise it returns a 1 (one).
+  on each specified file system.  Otherwise it returns a 1 (one) if
+  any part of the search failed.
 
-  If lsof detects an error and makes an unsuccessful exit, it
-  returns an exit code of 1 (one).
+  This behavior can be modified by calling lsof with -Q, which will
+  tell it to provide a successful exit code of 0 (zero) even if any
+  part of the file or filesystem search failed.
+
+  If lsof detects a generic (non-search) error during its execution,
+  it returns an exit code of 1 (one).  The -Q option will not
+  affect this behavior.
 
   You can use the exit code in a shell script to search for files
   on a file system and take action based on the result -- e.g.,
@@ -761,6 +767,18 @@
       echo "<file_system_name> has some users."
     else
       echo "<file_system_name> may have no users."
+    fi
+
+  The -Q option can help in certain circumstances.  For example, if
+  you want to log filesystem users without caring if there are no
+  users:
+
+    #!/bin/sh
+    lsof -Q <file_system_name>  > fs_users.log
+    if test $? -ne 0
+    then
+      echo "Error: Something actually went wrong!" 1>&2
+      exit 1
     fi
 
 
@@ -1003,6 +1021,13 @@ D.  Miscellaneous Lsof Options
 		-r.  Example:
 
 		    $ lsof -r30
+
+	-Q	tells lsof not to consider it an error if it was
+		given search terms and any part of the search came
+		up empty. This will silence any reports of missing
+		files to stderr. Additionally, lsof will exit with
+		a non-error code despite any missing files or
+		filesystems with no open files.
 
 	-v	displays information about the building of the
 		lsof executable.
